print(' '*6, 'A')
print(' '*5, 'B', 'B')
print(' '*4, 'C', ' ','C')
print(' '*3, 'D', ' ',' ','D')
print(' '*2, 'E', ' ',' ',' ','E')
print(' '*3, 'D', ' ',' ','D')
print(' '*4, 'C', ' ','C')
print(' '*5, 'B', 'B')
print(' '*6, 'A')